server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: backstage-provider

mybatis:
  configuration:
    map-underscore-to-camel-case: true

